apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployments/example-deployment.yaml
  - deployments/next-deployment.yaml
  - services/hello-service.yaml
  - services/next-service.yaml
  - ingress-routing.yaml
  - letsencrypt-galvanizer.yaml
