apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: my-wordpress
  namespace: default # or your desired namespace
spec:
  interval: 1h # how often to check for updates
  chart:
    spec:
      chart: wordpress
      version: "18.0.4"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system # the namespace where the HelmRepository is
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
